#ifndef __CONFIG_H__
#define __CONFIG_H__

#define CERT_BUFFER_SIZE 10*1024
#define PK_BUFFER_SIZE 2*1024

#define CERT_MIAS_PATH SE_MIAS_P11_KEY_NAME_PREFIX "CERT_TYPE_A"
#define PK_MIAS_PATH SE_MIAS_P11_KEY_NAME_PREFIX "PRIV_TYPE_A"

#endif
